### ISSUE TITLE
Локализация значении справочников

### ISSUE THREAD

**Issue by flabser** [flabser/NB3#1]
Необходимо добавить поля в country (пока в эту форму) для ввода локализованных значении. В форме имеются теги localizednames , где перечислены языки используемые в системе. Небходимо ровно столько же выводить полей и отправлять в форме . Название полей наверное формируем по принципу
englocalizedname
kazlocalizedname  и т.д.

**Comment by EvgeniyBurlyay** [comment]
исполнено
